name: Deploy Firebase Config and Push Code

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate firebaseConfig.js from GitHub Secrets
        run: |
          echo "export const firebaseConfig = {
            apiKey: '${{ secrets.FB_API_KEY }}',
            authDomain: '${{ secrets.FB_AUTH_DOMAIN }}',
            projectId: '${{ secrets.FB_PROJECT_ID }}',
            storageBucket: '${{ secrets.FB_STORAGE_BUCKET }}',
            messagingSenderId: '${{ secrets.FB_MESSAGING_SENDER_ID }}',
            appId: '${{ secrets.FB_APP_ID }}',
            measurementId: '${{ secrets.FB_MEASUREMENT_ID }}'
          };" > firebaseConfig.js

      - name: Commit firebaseConfig.js
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/firebaseConfig.js
          git commit -m "Auto-generate firebaseConfig.js from secrets"
          git push origin main
